DEBUG 2013-06-17 13:37:56,034 util 11152 140272960796416 (0.017) SELECT `django_session`.`session_key`, `django_session`.`session_data`, `django_session`.`expire_date` FROM `django_session` WHERE (`django_session`.`session_key` = 'gvn4519kjt5g5fmtknfe3neztmi34uts'  AND `django_session`.`expire_date` > '2013-06-17 20:37:55' ); args=('gvn4519kjt5g5fmtknfe3neztmi34uts', u'2013-06-17 20:37:55')
DEBUG 2013-06-17 13:37:56,093 util 11152 140272960796416 (0.017) SELECT `auth_user`.`id`, `auth_user`.`password`, `auth_user`.`last_login`, `auth_user`.`is_superuser`, `auth_user`.`username`, `auth_user`.`first_name`, `auth_user`.`last_name`, `auth_user`.`email`, `auth_user`.`is_staff`, `auth_user`.`is_active`, `auth_user`.`date_joined` FROM `auth_user` WHERE `auth_user`.`id` = 1 ; args=(1,)
WARNING 2013-06-17 13:37:56,335 base 11152 140272960796416 Not Found: /favicon.ico/
DEBUG 2013-06-17 13:37:57,288 util 11152 140272960796416 (0.017) SELECT `django_session`.`session_key`, `django_session`.`session_data`, `django_session`.`expire_date` FROM `django_session` WHERE (`django_session`.`session_key` = 'gvn4519kjt5g5fmtknfe3neztmi34uts'  AND `django_session`.`expire_date` > '2013-06-17 20:37:57' ); args=('gvn4519kjt5g5fmtknfe3neztmi34uts', u'2013-06-17 20:37:57')
DEBUG 2013-06-17 13:37:57,324 util 11152 140272960796416 (0.017) SELECT `auth_user`.`id`, `auth_user`.`password`, `auth_user`.`last_login`, `auth_user`.`is_superuser`, `auth_user`.`username`, `auth_user`.`first_name`, `auth_user`.`last_name`, `auth_user`.`email`, `auth_user`.`is_staff`, `auth_user`.`is_active`, `auth_user`.`date_joined` FROM `auth_user` WHERE `auth_user`.`id` = 1 ; args=(1,)
DEBUG 2013-06-17 13:37:57,361 util 11152 140272960796416 (0.017) SELECT `auth_user`.`id`, `auth_user`.`password`, `auth_user`.`last_login`, `auth_user`.`is_superuser`, `auth_user`.`username`, `auth_user`.`first_name`, `auth_user`.`last_name`, `auth_user`.`email`, `auth_user`.`is_staff`, `auth_user`.`is_active`, `auth_user`.`date_joined` FROM `auth_user` WHERE `auth_user`.`id` = 1 ; args=(1,)
DEBUG 2013-06-17 13:37:57,407 util 11152 140272960796416 (0.017) SELECT `auth_group`.`id` FROM `auth_group` INNER JOIN `auth_user_groups` ON (`auth_group`.`id` = `auth_user_groups`.`group_id`) WHERE `auth_user_groups`.`user_id` = 1 ; args=(1,)
DEBUG 2013-06-17 13:37:57,444 util 11152 140272960796416 (0.017) SELECT `auth_permission`.`id` FROM `auth_permission` INNER JOIN `auth_user_user_permissions` ON (`auth_permission`.`id` = `auth_user_user_permissions`.`permission_id`) INNER JOIN `django_content_type` ON (`auth_permission`.`content_type_id` = `django_content_type`.`id`) WHERE `auth_user_user_permissions`.`user_id` = 1  ORDER BY `django_content_type`.`app_label` ASC, `django_content_type`.`model` ASC, `auth_permission`.`codename` ASC; args=(1,)
DEBUG 2013-06-17 13:37:57,492 util 11152 140272960796416 (0.016) SELECT `django_content_type`.`id`, `django_content_type`.`name`, `django_content_type`.`app_label`, `django_content_type`.`model` FROM `django_content_type` WHERE (`django_content_type`.`model` = 'user'  AND `django_content_type`.`app_label` = 'auth' ); args=('user', u'auth')
DEBUG 2013-06-17 13:37:57,580 util 11152 140272960796416 (0.017) SELECT `auth_group`.`id`, `auth_group`.`name` FROM `auth_group`; args=()
DEBUG 2013-06-17 13:37:57,622 util 11152 140272960796416 (0.019) SELECT `auth_permission`.`id`, `auth_permission`.`name`, `auth_permission`.`content_type_id`, `auth_permission`.`codename`, `django_content_type`.`id`, `django_content_type`.`name`, `django_content_type`.`app_label`, `django_content_type`.`model` FROM `auth_permission` INNER JOIN `django_content_type` ON (`auth_permission`.`content_type_id` = `django_content_type`.`id`) ORDER BY `django_content_type`.`app_label` ASC, `django_content_type`.`model` ASC, `auth_permission`.`codename` ASC; args=()
DEBUG 2013-06-17 13:37:57,856 util 11152 140272960796416 (0.019) SELECT `django_session`.`session_key`, `django_session`.`session_data`, `django_session`.`expire_date` FROM `django_session` WHERE (`django_session`.`session_key` = 'gvn4519kjt5g5fmtknfe3neztmi34uts'  AND `django_session`.`expire_date` > '2013-06-17 20:37:57' ); args=('gvn4519kjt5g5fmtknfe3neztmi34uts', u'2013-06-17 20:37:57')
DEBUG 2013-06-17 13:37:57,894 util 11152 140272960796416 (0.018) SELECT `auth_user`.`id`, `auth_user`.`password`, `auth_user`.`last_login`, `auth_user`.`is_superuser`, `auth_user`.`username`, `auth_user`.`first_name`, `auth_user`.`last_name`, `auth_user`.`email`, `auth_user`.`is_staff`, `auth_user`.`is_active`, `auth_user`.`date_joined` FROM `auth_user` WHERE `auth_user`.`id` = 1 ; args=(1,)
WARNING 2013-06-17 13:37:58,158 base 11152 140272960796416 Not Found: /favicon.ico/
DEBUG 2013-06-17 13:38:10,375 util 11152 140272960796416 (0.018) SELECT `django_session`.`session_key`, `django_session`.`session_data`, `django_session`.`expire_date` FROM `django_session` WHERE (`django_session`.`session_key` = 'gvn4519kjt5g5fmtknfe3neztmi34uts'  AND `django_session`.`expire_date` > '2013-06-17 20:38:10' ); args=('gvn4519kjt5g5fmtknfe3neztmi34uts', u'2013-06-17 20:38:10')
DEBUG 2013-06-17 13:38:10,413 util 11152 140272960796416 (0.018) SELECT `auth_user`.`id`, `auth_user`.`password`, `auth_user`.`last_login`, `auth_user`.`is_superuser`, `auth_user`.`username`, `auth_user`.`first_name`, `auth_user`.`last_name`, `auth_user`.`email`, `auth_user`.`is_staff`, `auth_user`.`is_active`, `auth_user`.`date_joined` FROM `auth_user` WHERE `auth_user`.`id` = 1 ; args=(1,)
DEBUG 2013-06-17 13:38:10,451 util 11152 140272960796416 (0.018) SELECT `auth_user`.`id`, `auth_user`.`password`, `auth_user`.`last_login`, `auth_user`.`is_superuser`, `auth_user`.`username`, `auth_user`.`first_name`, `auth_user`.`last_name`, `auth_user`.`email`, `auth_user`.`is_staff`, `auth_user`.`is_active`, `auth_user`.`date_joined` FROM `auth_user` WHERE `auth_user`.`id` = 1 ; args=(1,)
DEBUG 2013-06-17 13:38:10,504 util 11152 140272960796416 (0.017) SELECT `auth_group`.`id` FROM `auth_group` INNER JOIN `auth_user_groups` ON (`auth_group`.`id` = `auth_user_groups`.`group_id`) WHERE `auth_user_groups`.`user_id` = 1 ; args=(1,)
DEBUG 2013-06-17 13:38:10,543 util 11152 140272960796416 (0.018) SELECT `auth_permission`.`id` FROM `auth_permission` INNER JOIN `auth_user_user_permissions` ON (`auth_permission`.`id` = `auth_user_user_permissions`.`permission_id`) INNER JOIN `django_content_type` ON (`auth_permission`.`content_type_id` = `django_content_type`.`id`) WHERE `auth_user_user_permissions`.`user_id` = 1  ORDER BY `django_content_type`.`app_label` ASC, `django_content_type`.`model` ASC, `auth_permission`.`codename` ASC; args=(1,)
DEBUG 2013-06-17 13:38:10,588 util 11152 140272960796416 (0.023) SELECT `auth_group`.`id`, `auth_group`.`name` FROM `auth_group` WHERE `auth_group`.`id` IN (1); args=(1,)
DEBUG 2013-06-17 13:38:10,658 util 11152 140272960796416 (0.023) SELECT (1) AS `a` FROM `auth_user` WHERE (`auth_user`.`username` = 'admin'  AND NOT (`auth_user`.`id` = 1 )) LIMIT 1; args=(u'admin', 1)
DEBUG 2013-06-17 13:38:10,697 util 11152 140272960796416 (0.019) SELECT (1) AS `a` FROM `auth_user` WHERE `auth_user`.`id` = 1  LIMIT 1; args=(1,)
DEBUG 2013-06-17 13:38:10,738 util 11152 140272960796416 (0.020) UPDATE `auth_user` SET `password` = 'pbkdf2_sha256$10000$QybOoIxq9k5J$URCQMFLvcn7BJYvdrXerebf2MeT7qOaHePMwG3m5aAI=', `last_login` = '2013-06-10 04:41:48', `is_superuser` = 1, `username` = 'admin', `first_name` = '', `last_name` = '', `email` = 'imran@splintera.com', `is_staff` = 1, `is_active` = 1, `date_joined` = '2013-06-10 04:40:50' WHERE `auth_user`.`id` = 1 ; args=(u'pbkdf2_sha256$10000$QybOoIxq9k5J$URCQMFLvcn7BJYvdrXerebf2MeT7qOaHePMwG3m5aAI=', u'2013-06-10 04:41:48', True, u'admin', u'', u'', u'imran@splintera.com', True, True, u'2013-06-10 04:40:50', 1)
DEBUG 2013-06-17 13:38:10,775 util 11152 140272960796416 (0.017) DELETE FROM `auth_user_groups` WHERE `auth_user_groups`.`user_id` = 1 ; args=(1,)
DEBUG 2013-06-17 13:38:10,814 util 11152 140272960796416 (0.017) SELECT `auth_user_groups`.`group_id` FROM `auth_user_groups` WHERE (`auth_user_groups`.`user_id` = 1  AND `auth_user_groups`.`group_id` IN (1)); args=(1, 1)
DEBUG 2013-06-17 13:38:10,855 util 11152 140272960796416 (0.023) INSERT INTO `auth_user_groups` (`user_id`, `group_id`) VALUES (1, 1); args=(1, 1)
DEBUG 2013-06-17 13:38:10,893 util 11152 140272960796416 (0.017) DELETE FROM `auth_user_user_permissions` WHERE `auth_user_user_permissions`.`user_id` = 1 ; args=(1,)
DEBUG 2013-06-17 13:38:10,931 util 11152 140272960796416 (0.017) INSERT INTO `django_admin_log` (`action_time`, `user_id`, `content_type_id`, `object_id`, `object_repr`, `action_flag`, `change_message`) VALUES ('2013-06-17 20:38:10', 1, 3, '1', 'admin', 2, 'Changed password and groups.'); args=[u'2013-06-17 20:38:10', 1, 3, u'1', u'admin', 2, u'Changed password and groups.']
DEBUG 2013-06-17 13:38:11,117 util 11152 140272960796416 (0.017) SELECT `django_session`.`session_key`, `django_session`.`session_data`, `django_session`.`expire_date` FROM `django_session` WHERE (`django_session`.`session_key` = 'gvn4519kjt5g5fmtknfe3neztmi34uts'  AND `django_session`.`expire_date` > '2013-06-17 20:38:10' ); args=('gvn4519kjt5g5fmtknfe3neztmi34uts', u'2013-06-17 20:38:10')
DEBUG 2013-06-17 13:38:11,152 util 11152 140272960796416 (0.016) SELECT `auth_user`.`id`, `auth_user`.`password`, `auth_user`.`last_login`, `auth_user`.`is_superuser`, `auth_user`.`username`, `auth_user`.`first_name`, `auth_user`.`last_name`, `auth_user`.`email`, `auth_user`.`is_staff`, `auth_user`.`is_active`, `auth_user`.`date_joined` FROM `auth_user` WHERE `auth_user`.`id` = 1 ; args=(1,)
DEBUG 2013-06-17 13:38:11,187 util 11152 140272960796416 (0.016) SELECT `auth_group`.`id`, `auth_group`.`name` FROM `auth_group`; args=()
DEBUG 2013-06-17 13:38:11,223 util 11152 140272960796416 (0.016) SELECT COUNT(DISTINCT `auth_user`.`id`) FROM `auth_user`; args=()
DEBUG 2013-06-17 13:38:11,262 util 11152 140272960796416 (0.016) SELECT DISTINCT `auth_user`.`id`, `auth_user`.`password`, `auth_user`.`last_login`, `auth_user`.`is_superuser`, `auth_user`.`username`, `auth_user`.`first_name`, `auth_user`.`last_name`, `auth_user`.`email`, `auth_user`.`is_staff`, `auth_user`.`is_active`, `auth_user`.`date_joined` FROM `auth_user` ORDER BY `auth_user`.`username` ASC, `auth_user`.`id` DESC; args=()
DEBUG 2013-06-17 13:38:11,518 util 11152 140272960796416 (0.017) SELECT `django_session`.`session_key`, `django_session`.`session_data`, `django_session`.`expire_date` FROM `django_session` WHERE (`django_session`.`session_key` = 'gvn4519kjt5g5fmtknfe3neztmi34uts'  AND `django_session`.`expire_date` > '2013-06-17 20:38:11' ); args=('gvn4519kjt5g5fmtknfe3neztmi34uts', u'2013-06-17 20:38:11')
DEBUG 2013-06-17 13:38:11,553 util 11152 140272960796416 (0.017) SELECT `auth_user`.`id`, `auth_user`.`password`, `auth_user`.`last_login`, `auth_user`.`is_superuser`, `auth_user`.`username`, `auth_user`.`first_name`, `auth_user`.`last_name`, `auth_user`.`email`, `auth_user`.`is_staff`, `auth_user`.`is_active`, `auth_user`.`date_joined` FROM `auth_user` WHERE `auth_user`.`id` = 1 ; args=(1,)
WARNING 2013-06-17 13:38:11,739 base 11152 140272960796416 Not Found: /favicon.ico/
WARNING 2013-06-17 17:05:38,181 base 13471 140275464148736 Not Found: /favicon.ico/
WARNING 2013-06-17 17:06:00,688 base 13848 139772924258048 Not Found: /favicon.ico/
WARNING 2013-06-17 17:28:25,121 base 15354 139786085988096 Not Found: /favicon.ico/
WARNING 2013-06-17 19:46:54,613 base 17751 140141486139136 Not Found: /favicon.ico/
WARNING 2013-06-17 19:50:02,791 base 17830 139884132038400 Not Found: /favicon.ico/
WARNING 2013-06-17 19:53:00,513 base 17867 140539470710528 Not Found: /favicon.ico/
WARNING 2013-06-17 19:53:36,412 base 17889 139649251014400 Not Found: /favicon.ico/
WARNING 2013-06-17 19:56:10,228 base 17920 140220196443904 Not Found: /favicon.ico/
WARNING 2013-06-17 19:56:41,846 base 17942 140568233277184 Not Found: /favicon.ico/
WARNING 2013-06-17 20:11:27,388 base 17942 140568233277184 Not Found: /favicon.ico/
WARNING 2013-06-17 20:18:15,389 base 18115 139752171689728 Not Found: /favicon.ico/
WARNING 2013-06-17 20:19:05,876 base 18154 139941897856768 Not Found: /favicon.ico/
WARNING 2013-06-17 20:19:44,044 base 18180 140583564949248 Not Found: /favicon.ico/
WARNING 2013-06-17 20:20:53,647 base 18217 140731764754176 Not Found: /favicon.ico/
WARNING 2013-06-17 20:28:07,087 base 18264 140676880656128 Not Found: /favicon.ico/
WARNING 2013-06-17 20:32:15,847 base 18339 139652740675328 Not Found: /favicon.ico/
WARNING 2013-06-17 20:32:43,406 base 18362 140727287805696 Not Found: /favicon.ico/
WARNING 2013-06-17 20:43:40,494 base 18396 140461188499200 Not Found: /favicon.ico/
WARNING 2013-06-17 20:44:53,138 base 18396 140461188499200 Not Found: /favicon.ico/
WARNING 2013-06-17 20:45:58,418 base 18396 140461188499200 Not Found: /favicon.ico/
WARNING 2013-06-17 20:46:35,968 base 18396 140461188499200 Not Found: /favicon.ico/
WARNING 2013-06-17 20:48:51,879 base 18396 140461188499200 Not Found: /favicon.ico/
WARNING 2013-06-17 20:52:45,321 base 18396 140461188499200 Not Found: /favicon.ico/
WARNING 2013-06-17 20:55:47,578 base 18396 140461188499200 Not Found: /favicon.ico/
WARNING 2013-06-18 15:10:07,406 base 3516 140338308044544 Not Found: /favicon.ico/
WARNING 2013-06-18 15:10:32,629 base 3516 140338308044544 Not Found: /favicon.ico/
WARNING 2013-06-18 15:10:52,403 base 5387 140507742525184 Not Found: /favicon.ico/
WARNING 2013-06-18 15:10:58,379 base 5387 140507742525184 Not Found: /favicon.ico/
WARNING 2013-06-18 21:12:48,421 base 5432 140695411095296 Not Found: /favicon.ico/
WARNING 2013-06-18 21:14:01,988 base 5432 140695411095296 Not Found: /favicon.ico/
ERROR 2013-06-18 21:46:19,879 base 11297 140240931829504 Internal Server Error: /
Traceback (most recent call last):
  File "/home/imran/Code/splintera-web/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 109, in get_response
    response = middleware_method(request, callback, callback_args, callback_kwargs)
  File "/home/imran/Code/splintera-web/venv/local/lib/python2.7/site-packages/splintera_client/tracer.py", line 23, in process_view
    return trace(view_func)(request, *view_args, **view_kwargs)
  File "/home/imran/Code/splintera-web/venv/local/lib/python2.7/site-packages/splintera_client/tracer.py", line 161, in wrapper
    result = f(*arg, **kw)
  File "/home/imran/Code/splintera-web/splintera/views.py", line 19, in dashboard
    for id, file_name, function_name in cursor.fetchall():
NameError: global name 'cursor' is not defined
WARNING 2013-06-18 21:46:20,431 base 11297 140240931829504 Not Found: /favicon.ico/
WARNING 2013-06-18 21:46:34,427 base 11481 140426505877248 Not Found: /favicon.ico/
WARNING 2013-06-18 22:05:41,533 base 11481 140426505877248 Not Found: /favicon.ico/
WARNING 2013-06-18 22:32:59,772 base 11888 140437200709376 Not Found: /favicon.ico/
WARNING 2013-06-19 07:12:18,465 base 15229 139920917407488 Not Found: /favicon.ico/
WARNING 2013-06-19 07:12:49,228 base 15229 139920917407488 Not Found: /favicon.ico/
WARNING 2013-06-19 07:23:28,159 base 15272 140305569183488 Not Found: /favicon.ico/
ERROR 2013-06-19 07:23:36,585 base 15272 140305569183488 Internal Server Error: /code/22
Traceback (most recent call last):
  File "/home/imran/Code/splintera-web/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 115, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/home/imran/Code/splintera-web/splintera/views.py", line 29, in code
    result = cur.execute(query, (trace_id))
  File "/home/imran/Code/splintera-web/venv/local/lib/python2.7/site-packages/MySQLdb/cursors.py", line 159, in execute
    query = query % db.literal(args)
TypeError: %d format: a number is required, not str
WARNING 2013-06-19 07:23:37,055 base 15272 140305569183488 Not Found: /favicon.ico/
ERROR 2013-06-19 07:24:14,573 base 15358 140650087442176 Internal Server Error: /code/22
Traceback (most recent call last):
  File "/home/imran/Code/splintera-web/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 115, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/home/imran/Code/splintera-web/splintera/views.py", line 29, in code
    result = cur.execute(query, (int(trace_id)))
  File "/home/imran/Code/splintera-web/venv/local/lib/python2.7/site-packages/MySQLdb/cursors.py", line 159, in execute
    query = query % db.literal(args)
TypeError: %d format: a number is required, not str
WARNING 2013-06-19 07:24:14,927 base 15358 140650087442176 Not Found: /favicon.ico/
WARNING 2013-06-19 07:24:47,470 base 15368 140473406183168 Not Found: /favicon.ico/
WARNING 2013-06-19 07:26:19,781 base 15368 140473406183168 Not Found: /favicon.ico/
WARNING 2013-06-19 07:28:42,586 base 15368 140473406183168 Not Found: /favicon.ico/
WARNING 2013-06-19 07:34:15,296 base 15507 140387008661248 Not Found: /favicon.ico/
WARNING 2013-06-19 07:36:15,386 base 15507 140387008661248 Not Found: /favicon.ico/
WARNING 2013-06-19 07:36:46,393 base 15507 140387008661248 Not Found: /favicon.ico/
WARNING 2013-06-19 07:39:51,524 base 15507 140387008661248 Not Found: /favicon.ico/
WARNING 2013-06-19 07:40:05,922 base 15507 140387008661248 Not Found: /favicon.ico/
WARNING 2013-06-19 07:43:52,224 base 15714 139792906528512 Not Found: /favicon.ico/
WARNING 2013-06-19 07:44:22,614 base 15714 139792906528512 Not Found: /favicon.ico/
WARNING 2013-06-19 08:02:10,085 base 16284 140507477915392 Not Found: /favicon.ico/
WARNING 2013-06-19 08:02:51,343 base 16297 139875810539264 Not Found: /favicon.ico/
WARNING 2013-06-19 08:03:05,588 base 16308 140285241718528 Not Found: /favicon.ico/
WARNING 2013-06-19 08:04:39,267 base 16308 140285241718528 Not Found: /favicon.ico/
WARNING 2013-06-19 08:05:16,831 base 16308 140285241718528 Not Found: /favicon.ico/
WARNING 2013-06-19 08:07:36,191 base 16351 139876949239552 Not Found: /favicon.ico/
WARNING 2013-06-19 08:08:11,863 base 16367 140501219120896 Not Found: /favicon.ico/
WARNING 2013-06-19 08:08:46,658 base 16367 140501219120896 Not Found: /favicon.ico/
WARNING 2013-06-19 11:07:48,069 base 16367 140501219120896 Not Found: /favicon.ico/
WARNING 2013-06-19 11:08:20,720 base 19985 140730063873792 Not Found: /favicon.ico/
WARNING 2013-06-19 11:09:05,545 base 19985 140730063873792 Not Found: /favicon.ico/
WARNING 2013-06-19 11:21:11,078 base 20157 140652895311616 Not Found: /favicon.ico/
WARNING 2013-06-19 11:22:10,676 base 20172 140528591214336 Not Found: /favicon.ico/
WARNING 2013-06-19 11:23:20,095 base 20216 140022586844928 Not Found: /favicon.ico/
WARNING 2013-06-19 11:28:41,028 base 20227 140703513151232 Not Found: /favicon.ico/
WARNING 2013-06-19 11:28:54,801 base 20227 140703513151232 Not Found: /favicon.ico/
ERROR 2013-06-24 21:13:05,351 base 934 140396642432768 Internal Server Error: /code/22
Traceback (most recent call last):
  File "/home/imran/Code/splintera-web/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 115, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/home/imran/Code/splintera-web/splintera/views.py", line 35, in code
    lines_executed = map(lambda line: int(line) - int(start_line_number), row[1])
  File "/home/imran/Code/splintera-web/splintera/views.py", line 35, in <lambda>
    lines_executed = map(lambda line: int(line) - int(start_line_number), row[1])
ValueError: invalid literal for int() with base 10: '['
WARNING 2013-06-24 21:13:06,074 base 934 140396642432768 Not Found: /favicon.ico/
WARNING 2013-06-24 21:13:49,046 base 992 140217730201344 Not Found: /favicon.ico/
WARNING 2013-06-24 21:26:48,124 base 1030 139864838498048 Not Found: /favicon.ico/
WARNING 2013-06-24 21:28:16,691 base 1030 139864838498048 Not Found: /favicon.ico/
WARNING 2013-06-24 21:30:09,478 base 1030 139864838498048 Not Found: /favicon.ico/
WARNING 2013-06-24 21:30:55,950 base 1030 139864838498048 Not Found: /favicon.ico/
WARNING 2013-06-24 21:36:41,351 base 1030 139864838498048 Not Found: /favicon.ico/
WARNING 2013-06-24 21:44:52,639 base 1030 139864838498048 Not Found: /favicon.ico/
WARNING 2013-06-24 21:45:20,299 base 1030 139864838498048 Not Found: /favicon.ico/
WARNING 2013-06-24 21:47:06,325 base 1030 139864838498048 Not Found: /favicon.ico/
WARNING 2013-06-24 21:48:50,810 base 1030 139864838498048 Not Found: /favicon.ico/
WARNING 2013-06-24 21:49:50,421 base 1030 139864838498048 Not Found: /favicon.ico/
WARNING 2013-06-24 21:57:19,801 base 1030 139864838498048 Not Found: /favicon.ico/
WARNING 2013-06-24 22:00:46,903 base 1030 139864838498048 Not Found: /favicon.ico/
WARNING 2013-06-24 22:06:02,293 base 1030 139864838498048 Not Found: /favicon.ico/
WARNING 2013-06-24 22:07:38,831 base 1030 139864838498048 Not Found: /favicon.ico/
WARNING 2013-06-24 22:08:17,129 base 1030 139864838498048 Not Found: /favicon.ico/
WARNING 2013-06-24 22:08:37,948 base 1030 139864838498048 Not Found: /favicon.ico/
WARNING 2013-06-24 22:10:15,112 base 1030 139864838498048 Not Found: /favicon.ico/
WARNING 2013-06-24 22:12:28,107 base 1030 139864838498048 Not Found: /favicon.ico/
WARNING 2013-06-24 22:13:25,075 base 1030 139864838498048 Not Found: /favicon.ico/
WARNING 2013-06-24 22:16:38,799 base 1030 139864838498048 Not Found: /favicon.ico/
WARNING 2013-06-24 22:17:13,391 base 1030 139864838498048 Not Found: /favicon.ico/
WARNING 2013-06-24 22:17:35,253 base 1030 139864838498048 Not Found: /favicon.ico/
WARNING 2013-06-24 22:22:08,076 base 2474 139967987263232 Not Found: /favicon.ico/
ERROR 2013-06-24 22:22:26,089 base 2474 139967987263232 Internal Server Error: /code/22
Traceback (most recent call last):
  File "/home/imran/Code/splintera-web/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 115, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/home/imran/Code/splintera-web/splintera/views.py", line 43, in code
    return render_to_response('code.html', {"code": code_lines, "lines_executed": lines_executed })
  File "/home/imran/Code/splintera-web/venv/local/lib/python2.7/site-packages/django/shortcuts/__init__.py", line 29, in render_to_response
    return HttpResponse(loader.render_to_string(*args, **kwargs), **httpresponse_kwargs)
  File "/home/imran/Code/splintera-web/venv/local/lib/python2.7/site-packages/django/template/loader.py", line 170, in render_to_string
    t = get_template(template_name)
  File "/home/imran/Code/splintera-web/venv/local/lib/python2.7/site-packages/django/template/loader.py", line 146, in get_template
    template, origin = find_template(template_name)
  File "/home/imran/Code/splintera-web/venv/local/lib/python2.7/site-packages/django/template/loader.py", line 135, in find_template
    source, display_name = loader(name, dirs)
  File "/home/imran/Code/splintera-web/venv/local/lib/python2.7/site-packages/django/template/loader.py", line 43, in __call__
    return self.load_template(template_name, template_dirs)
  File "/home/imran/Code/splintera-web/venv/local/lib/python2.7/site-packages/django/template/loader.py", line 49, in load_template
    template = get_template_from_string(source, origin, template_name)
  File "/home/imran/Code/splintera-web/venv/local/lib/python2.7/site-packages/django/template/loader.py", line 157, in get_template_from_string
    return Template(source, origin, name)
  File "/home/imran/Code/splintera-web/venv/local/lib/python2.7/site-packages/django/template/base.py", line 125, in __init__
    self.nodelist = compile_string(template_string, origin)
  File "/home/imran/Code/splintera-web/venv/local/lib/python2.7/site-packages/django/template/base.py", line 153, in compile_string
    return parser.parse()
  File "/home/imran/Code/splintera-web/venv/local/lib/python2.7/site-packages/django/template/base.py", line 274, in parse
    compiled_result = compile_func(self, token)
  File "/home/imran/Code/splintera-web/venv/local/lib/python2.7/site-packages/django/template/defaulttags.py", line 767, in do_for
    nodelist_loop = parser.parse(('empty', 'endfor',))
  File "/home/imran/Code/splintera-web/venv/local/lib/python2.7/site-packages/django/template/base.py", line 253, in parse
    filter_expression = self.compile_filter(token.contents)
  File "/home/imran/Code/splintera-web/venv/local/lib/python2.7/site-packages/django/template/base.py", line 353, in compile_filter
    return FilterExpression(token, self)
  File "/home/imran/Code/splintera-web/venv/local/lib/python2.7/site-packages/django/template/base.py", line 570, in __init__
    "from '%s'" % (token[upto:], token))
TemplateSyntaxError: Could not parse the remainder: '+1' from 'line+1'
WARNING 2013-06-24 22:22:26,701 base 2474 139967987263232 Not Found: /favicon.ico/
WARNING 2013-06-24 22:23:41,413 base 2474 139967987263232 Not Found: /favicon.ico/
WARNING 2013-06-27 08:29:59,581 base 25271 139744811886336 Not Found: /favicon.ico/
WARNING 2013-06-27 08:30:21,018 base 25271 139744811886336 Not Found: /favicon.ico/
ERROR 2013-06-27 08:46:24,308 base 26780 140621438445312 Internal Server Error: /code/22
Traceback (most recent call last):
  File "/home/imran/Code/splintera-web/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 115, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/home/imran/Code/splintera-web/splintera/views.py", line 44, in code
    return render_to_response('code.html', {"code": code_lines, "lines_executed": lines_executed, "num_lines": num_lines })
  File "/home/imran/Code/splintera-web/venv/local/lib/python2.7/site-packages/django/shortcuts/__init__.py", line 29, in render_to_response
    return HttpResponse(loader.render_to_string(*args, **kwargs), **httpresponse_kwargs)
  File "/home/imran/Code/splintera-web/venv/local/lib/python2.7/site-packages/django/template/loader.py", line 172, in render_to_string
    return t.render(Context(dictionary))
  File "/home/imran/Code/splintera-web/venv/local/lib/python2.7/site-packages/django/template/base.py", line 140, in render
    return self._render(context)
  File "/home/imran/Code/splintera-web/venv/local/lib/python2.7/site-packages/django/template/base.py", line 134, in _render
    return self.nodelist.render(context)
  File "/home/imran/Code/splintera-web/venv/local/lib/python2.7/site-packages/django/template/base.py", line 830, in render
    bit = self.render_node(node, context)
  File "/home/imran/Code/splintera-web/venv/local/lib/python2.7/site-packages/django/template/base.py", line 844, in render_node
    return node.render(context)
  File "/home/imran/Code/splintera-web/venv/local/lib/python2.7/site-packages/django/template/defaulttags.py", line 147, in render
    values = list(values)
TypeError: 'int' object is not iterable
WARNING 2013-06-27 08:46:24,793 base 26780 140621438445312 Not Found: /favicon.ico/
WARNING 2013-06-27 08:48:50,545 base 27249 140723496269568 Not Found: /favicon.ico/
WARNING 2013-06-27 08:49:05,435 base 27249 140723496269568 Not Found: /favicon.ico/
WARNING 2013-06-27 08:49:30,402 base 27249 140723496269568 Not Found: /favicon.ico/
WARNING 2013-06-27 08:54:27,033 base 27249 140723496269568 Not Found: /favicon.ico/
WARNING 2013-06-27 08:55:04,374 base 27249 140723496269568 Not Found: /favicon.ico/
ERROR 2013-06-27 09:01:10,468 base 28207 139974555399936 Internal Server Error: /code/22
Traceback (most recent call last):
  File "/home/imran/Code/splintera-web/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 115, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/home/imran/Code/splintera-web/splintera/views.py", line 43, in code
    return render_to_response('code.html', {"code": code_lines, "lines_executed": lines_executed, "input_parameters": input_parameters, "return_value": return_value })
NameError: global name 'input_parameters' is not defined
WARNING 2013-06-27 09:01:10,834 base 28207 139974555399936 Not Found: /favicon.ico/
WARNING 2013-06-27 09:01:49,578 base 28897 139977659188992 Not Found: /favicon.ico/
WARNING 2013-06-27 09:05:42,264 base 28897 139977659188992 Not Found: /code/bootstrap.min.css
WARNING 2013-06-27 09:05:42,268 base 28897 139977650796288 Not Found: /code/bootstrap.min.js
WARNING 2013-06-27 09:05:42,622 base 28897 139977650796288 Not Found: /favicon.ico/
WARNING 2013-06-27 09:06:54,437 base 28897 139977659188992 Not Found: /favicon.ico/
WARNING 2013-06-27 09:07:13,984 base 28897 139977632802560 Not Found: /favicon.ico/
WARNING 2013-06-27 09:09:55,639 base 28897 139977632802560 Not Found: /favicon.ico/
WARNING 2013-06-27 09:14:42,865 base 28897 139977413359360 Not Found: /favicon.ico/
WARNING 2013-06-27 09:15:00,543 base 28897 139977413359360 Not Found: /favicon.ico/
WARNING 2013-06-27 09:19:11,783 base 28897 139977413359360 Not Found: /favicon.ico/
WARNING 2013-06-27 09:19:40,692 base 28897 139977413359360 Not Found: /favicon.ico/
WARNING 2013-06-27 09:19:54,500 base 28897 139977413359360 Not Found: /favicon.ico/
WARNING 2013-06-27 10:07:45,596 base 28897 139977413359360 Not Found: /favicon.ico/
WARNING 2013-06-27 10:08:11,578 base 28897 139977413359360 Not Found: /favicon.ico/
WARNING 2013-06-27 10:13:05,801 base 28897 139977413359360 Not Found: /favicon.ico/
WARNING 2013-06-27 10:16:47,400 base 28897 139977413359360 Not Found: /favicon.ico/
WARNING 2013-06-27 10:17:19,685 base 28897 139977413359360 Not Found: /favicon.ico/
WARNING 2013-06-27 10:19:30,594 base 28897 139977413359360 Not Found: /favicon.ico/
WARNING 2013-06-27 10:35:58,515 base 28897 139977413359360 Not Found: /favicon.ico/
WARNING 2013-06-27 10:36:40,483 base 28897 139977413359360 Not Found: /favicon.ico/
WARNING 2013-06-27 10:37:18,675 base 28897 139977413359360 Not Found: /favicon.ico/
WARNING 2013-06-27 10:38:51,379 base 28897 139977413359360 Not Found: /favicon.ico/
WARNING 2013-06-28 22:00:49,783 base 29000 140436429596416 Not Found: /favicon.ico/
WARNING 2013-06-30 12:54:33,523 base 22914 139714061502208 Not Found: /favicon.ico/
WARNING 2013-06-30 12:55:50,520 base 22961 139646692484864 Not Found: /favicon.ico/
WARNING 2013-06-30 14:28:34,898 base 23692 140426133280512 Not Found: /favicon.ico/
WARNING 2013-06-30 14:30:46,923 base 23751 140551219193600 Not Found: /favicon.ico/
WARNING 2013-06-30 15:14:20,052 base 24082 139639946336000 Not Found: /favicon.ico/
WARNING 2013-06-30 17:42:56,758 base 24933 140694282307328 Not Found: /favicon.ico/
WARNING 2013-06-30 17:44:57,338 base 24975 139877018498816 Not Found: /favicon.ico/
WARNING 2013-06-30 17:55:22,841 base 25185 140064885344000 Not Found: /favicon.ico/
WARNING 2013-06-30 17:58:02,075 base 25234 140221882558208 Not Found: /favicon.ico/
WARNING 2013-06-30 18:38:15,615 base 25666 140221436716800 Not Found: /favicon.ico/
WARNING 2013-06-30 18:40:50,568 base 25797 140173802809088 Not Found: /favicon.ico/
WARNING 2013-06-30 18:41:38,753 base 25833 139808465106688 Not Found: /favicon.ico/
WARNING 2013-06-30 19:08:54,016 base 26032 140416095610624 Not Found: /favicon.ico/
WARNING 2013-07-03 20:45:52,272 base 18191 140585545492224 Not Found: /favicon.ico/
ERROR 2013-07-03 21:09:31,458 base 18293 140144891983616 Internal Server Error: /
Traceback (most recent call last):
  File "/home/imran/Code/splintera-web/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 109, in get_response
    response = middleware_method(request, callback, callback_args, callback_kwargs)
  File "/home/imran/Code/splintera-web/venv/local/lib/python2.7/site-packages/splintera_client/tracer.py", line 24, in process_view
    return trace(view_func)(request, *view_args, **view_kwargs)
  File "/home/imran/Code/splintera-web/venv/local/lib/python2.7/site-packages/splintera_client/tracer.py", line 180, in wrapper
    result = f(*arg, **kw)
  File "/home/imran/Code/splintera-web/splintera/views.py", line 13, in dashboard
    response = urllib2.urlopen('http://python.org/')
  File "/usr/lib/python2.7/urllib2.py", line 126, in urlopen
    return _opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 400, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 418, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 378, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 1207, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "/usr/lib/python2.7/urllib2.py", line 1174, in do_open
    h.request(req.get_method(), req.get_selector(), req.data, headers)
  File "/usr/lib/python2.7/httplib.py", line 958, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 992, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 954, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 814, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 776, in send
    self.connect()
  File "/usr/lib/python2.7/httplib.py", line 757, in connect
    self.timeout, self.source_address)
  File "/usr/lib/python2.7/socket.py", line 537, in create_connection
    def create_connection(address, timeout=_GLOBAL_DEFAULT_TIMEOUT,
  File "/home/imran/Code/splintera-web/venv/local/lib/python2.7/site-packages/splintera_client/tracer.py", line 241, in trace_calls_and_returns
    print inspect.getframeinfo(parent)
  File "/usr/lib/python2.7/inspect.py", line 999, in getframeinfo
    lineno = frame.f_lineno
AttributeError: 'tuple' object has no attribute 'f_lineno'
WARNING 2013-07-03 21:09:31,946 base 18293 140144891983616 Not Found: /favicon.ico/
WARNING 2013-07-03 21:10:50,505 base 18512 139671245936384 Not Found: /favicon.ico/
WARNING 2013-07-03 21:21:40,757 base 18713 140475898001152 Not Found: /favicon.ico/
ERROR 2013-07-03 21:33:50,075 base 18956 140536305440512 Internal Server Error: /
Traceback (most recent call last):
  File "/home/imran/Code/splintera-web/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 109, in get_response
    response = middleware_method(request, callback, callback_args, callback_kwargs)
  File "/home/imran/Code/splintera-web/venv/local/lib/python2.7/site-packages/splintera_client/tracer.py", line 24, in process_view
    return trace(view_func)(request, *view_args, **view_kwargs)
  File "/home/imran/Code/splintera-web/venv/local/lib/python2.7/site-packages/splintera_client/tracer.py", line 180, in wrapper
    result = f(*arg, **kw)
  File "/home/imran/Code/splintera-web/splintera/views.py", line 10, in dashboard
    def dashboard(request):
  File "/home/imran/Code/splintera-web/venv/local/lib/python2.7/site-packages/splintera_client/tracer.py", line 244, in trace_calls_and_returns
    if string.find(co,' open(')!=-1:
  File "/usr/lib/python2.7/string.py", line 361, in find
    return s.find(*args)
AttributeError: 'code' object has no attribute 'find'
WARNING 2013-07-03 21:33:50,484 base 18956 140536305440512 Not Found: /favicon.ico/
ERROR 2013-07-03 21:43:13,557 base 19133 140287136315136 Internal Server Error: /
Traceback (most recent call last):
  File "/home/imran/Code/splintera-web/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 109, in get_response
    response = middleware_method(request, callback, callback_args, callback_kwargs)
  File "/home/imran/Code/splintera-web/venv/local/lib/python2.7/site-packages/splintera_client/tracer.py", line 24, in process_view
    return trace(view_func)(request, *view_args, **view_kwargs)
  File "/home/imran/Code/splintera-web/venv/local/lib/python2.7/site-packages/splintera_client/tracer.py", line 180, in wrapper
    result = f(*arg, **kw)
  File "/home/imran/Code/splintera-web/splintera/views.py", line 10, in dashboard
    def dashboard(request):
  File "/home/imran/Code/splintera-web/venv/local/lib/python2.7/site-packages/splintera_client/tracer.py", line 245, in trace_calls_and_returns
    if string.find(code,' open(')!=-1:
  File "/usr/lib/python2.7/string.py", line 361, in find
    return s.find(*args)
AttributeError: 'list' object has no attribute 'find'
WARNING 2013-07-03 21:43:13,940 base 19133 140287136315136 Not Found: /favicon.ico/
ERROR 2013-07-03 21:44:14,586 base 19202 140107489675008 Internal Server Error: /
Traceback (most recent call last):
  File "/home/imran/Code/splintera-web/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 109, in get_response
    response = middleware_method(request, callback, callback_args, callback_kwargs)
  File "/home/imran/Code/splintera-web/venv/local/lib/python2.7/site-packages/splintera_client/tracer.py", line 24, in process_view
    return trace(view_func)(request, *view_args, **view_kwargs)
  File "/home/imran/Code/splintera-web/venv/local/lib/python2.7/site-packages/splintera_client/tracer.py", line 180, in wrapper
    result = f(*arg, **kw)
  File "/home/imran/Code/splintera-web/splintera/views.py", line 13, in dashboard
    response = urllib2.urlopen('http://python.org/')
  File "/usr/lib/python2.7/urllib2.py", line 126, in urlopen
    return _opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 385, in open
    req = Request(fullurl, data)
  File "/usr/lib/python2.7/urllib2.py", line 211, in __init__
    origin_req_host = request_host(self)
  File "/usr/lib/python2.7/urllib2.py", line 185, in request_host
    host = urlparse.urlparse(url)[1]
  File "/usr/lib/python2.7/urlparse.py", line 135, in urlparse
    tuple = urlsplit(url, scheme, allow_fragments)
  File "/usr/lib/python2.7/urlparse.py", line 188, in urlsplit
    v = SplitResult(scheme, netloc, url, query, fragment)
  File "<string>", line 8, in __new__
  File "/home/imran/Code/splintera-web/venv/local/lib/python2.7/site-packages/splintera_client/tracer.py", line 245, in trace_calls_and_returns
    if string.find(string.join(code),' open(')!=-1:
  File "/usr/lib/python2.7/string.py", line 318, in join
    return sep.join(words)
TypeError
WARNING 2013-07-03 21:44:14,990 base 19202 140107489675008 Not Found: /favicon.ico/
WARNING 2013-07-03 21:49:11,464 base 19264 139733489288960 Not Found: /favicon.ico/
ERROR 2013-07-03 22:17:23,883 base 19441 140176075310848 Internal Server Error: /
Traceback (most recent call last):
  File "/home/imran/Code/splintera-web/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 109, in get_response
    response = middleware_method(request, callback, callback_args, callback_kwargs)
  File "/home/imran/Code/splintera-web/venv/local/lib/python2.7/site-packages/splintera_client/tracer.py", line 24, in process_view
    return trace(view_func)(request, *view_args, **view_kwargs)
  File "/home/imran/Code/splintera-web/venv/local/lib/python2.7/site-packages/splintera_client/tracer.py", line 180, in wrapper
    result = f(*arg, **kw)
  File "/home/imran/Code/splintera-web/splintera/views.py", line 13, in dashboard
    response = urllib2.urlopen('http://python.org/')
  File "/usr/lib/python2.7/urllib2.py", line 126, in urlopen
    return _opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 385, in open
    req = Request(fullurl, data)
  File "/usr/lib/python2.7/urllib2.py", line 211, in __init__
    origin_req_host = request_host(self)
  File "/usr/lib/python2.7/urllib2.py", line 185, in request_host
    host = urlparse.urlparse(url)[1]
  File "/usr/lib/python2.7/urlparse.py", line 135, in urlparse
    tuple = urlsplit(url, scheme, allow_fragments)
  File "/usr/lib/python2.7/urlparse.py", line 188, in urlsplit
    v = SplitResult(scheme, netloc, url, query, fragment)
  File "<string>", line 8, in __new__
  File "/home/imran/Code/splintera-web/venv/local/lib/python2.7/site-packages/splintera_client/tracer.py", line 245, in trace_calls_and_returns
    if len(code)>0:
TypeError: object of type 'NoneType' has no len()
WARNING 2013-07-03 22:17:24,291 base 19441 140176075310848 Not Found: /favicon.ico/
WARNING 2013-07-03 22:23:52,518 base 19532 140497171511040 Not Found: /favicon.ico/
WARNING 2013-07-03 22:33:06,562 base 19666 139725439674112 Not Found: /favicon.ico/
WARNING 2013-07-03 22:35:21,079 base 19715 139828411700992 Not Found: /favicon.ico/
WARNING 2013-07-03 22:36:26,717 base 19746 140276875687680 Not Found: /favicon.ico/
ERROR 2013-07-03 22:40:12,526 base 19835 140225215657728 Internal Server Error: /
Traceback (most recent call last):
  File "/home/imran/Code/splintera-web/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 109, in get_response
    response = middleware_method(request, callback, callback_args, callback_kwargs)
  File "/home/imran/Code/splintera-web/venv/local/lib/python2.7/site-packages/splintera_client/tracer.py", line 24, in process_view
    return trace(view_func)(request, *view_args, **view_kwargs)
  File "/home/imran/Code/splintera-web/venv/local/lib/python2.7/site-packages/splintera_client/tracer.py", line 180, in wrapper
    result = f(*arg, **kw)
  File "/home/imran/Code/splintera-web/splintera/views.py", line 10, in dashboard
    def dashboard(request):
  File "/home/imran/Code/splintera-web/venv/local/lib/python2.7/site-packages/splintera_client/tracer.py", line 253, in trace_calls_and_returns
    print 'dashboard:' + inspect.getframeinfo(frame)[3]
TypeError: cannot concatenate 'str' and 'list' objects
WARNING 2013-07-03 22:40:12,886 base 19835 140225215657728 Not Found: /favicon.ico/
WARNING 2013-07-03 22:40:36,347 base 19865 140621942810368 Not Found: /favicon.ico/
ERROR 2013-07-03 22:42:47,714 base 19929 140364716308224 Internal Server Error: /
Traceback (most recent call last):
  File "/home/imran/Code/splintera-web/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 109, in get_response
    response = middleware_method(request, callback, callback_args, callback_kwargs)
  File "/home/imran/Code/splintera-web/venv/local/lib/python2.7/site-packages/splintera_client/tracer.py", line 24, in process_view
    return trace(view_func)(request, *view_args, **view_kwargs)
  File "/home/imran/Code/splintera-web/venv/local/lib/python2.7/site-packages/splintera_client/tracer.py", line 180, in wrapper
    result = f(*arg, **kw)
  File "/home/imran/Code/splintera-web/splintera/views.py", line 12, in dashboard
    import urllib2
  File "/home/imran/Code/splintera-web/splintera/views.py", line 12, in dashboard
    import urllib2
  File "/home/imran/Code/splintera-web/venv/local/lib/python2.7/site-packages/splintera_client/tracer.py", line 225, in trace_lines
    if string.find(' '.join(code),' open(')!=-1:
TypeError
WARNING 2013-07-03 22:42:48,091 base 19929 140364716308224 Not Found: /favicon.ico/
ERROR 2013-07-03 22:43:43,182 base 19970 140311650117376 Internal Server Error: /
Traceback (most recent call last):
  File "/home/imran/Code/splintera-web/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 109, in get_response
    response = middleware_method(request, callback, callback_args, callback_kwargs)
  File "/home/imran/Code/splintera-web/venv/local/lib/python2.7/site-packages/splintera_client/tracer.py", line 24, in process_view
    return trace(view_func)(request, *view_args, **view_kwargs)
  File "/home/imran/Code/splintera-web/venv/local/lib/python2.7/site-packages/splintera_client/tracer.py", line 180, in wrapper
    result = f(*arg, **kw)
  File "/home/imran/Code/splintera-web/splintera/views.py", line 12, in dashboard
    import urllib2
  File "/home/imran/Code/splintera-web/splintera/views.py", line 12, in dashboard
    import urllib2
  File "/home/imran/Code/splintera-web/venv/local/lib/python2.7/site-packages/splintera_client/tracer.py", line 218, in trace_lines
    func_name = code.co_name
UnboundLocalError: local variable 'code' referenced before assignment
WARNING 2013-07-03 22:43:43,573 base 19970 140311650117376 Not Found: /favicon.ico/
WARNING 2013-07-03 22:44:18,173 base 20034 140338521888512 Not Found: /favicon.ico/
WARNING 2013-07-04 07:58:17,527 base 22015 139866843485952 Not Found: /favicon.ico/
ERROR 2013-07-04 08:32:29,879 base 22986 139660297168640 Internal Server Error: /
Traceback (most recent call last):
  File "/home/imran/Code/splintera-web/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 109, in get_response
    response = middleware_method(request, callback, callback_args, callback_kwargs)
  File "/home/imran/Code/splintera-web/venv/local/lib/python2.7/site-packages/splintera_client/tracer.py", line 24, in process_view
    return trace(view_func)(request, *view_args, **view_kwargs)
  File "/home/imran/Code/splintera-web/venv/local/lib/python2.7/site-packages/splintera_client/tracer.py", line 180, in wrapper
    result = f(*arg, **kw)
  File "/home/imran/Code/splintera-web/splintera/views.py", line 13, in dashboard
    response = urllib2.urlopen('http://python.org/')
  File "/usr/lib/python2.7/urllib2.py", line 126, in urlopen
    return _opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 382, in open
    def open(self, fullurl, data=None, timeout=socket._GLOBAL_DEFAULT_TIMEOUT):
  File "/home/imran/Code/splintera-web/venv/local/lib/python2.7/site-packages/splintera_client/tracer.py", line 262, in trace_calls_and_returns
    current_trace['per_line_dependencies'].setdefault([frame_details[1]],[]).append('filesystem')
TypeError: unhashable type: 'list'
WARNING 2013-07-04 08:32:30,255 base 22986 139660297168640 Not Found: /favicon.ico/
WARNING 2013-07-04 08:36:04,254 base 23051 139681043830528 Not Found: /favicon.ico/
ERROR 2013-07-05 10:25:46,517 base 6756 140163143399168 Internal Server Error: /
Traceback (most recent call last):
  File "/home/imran/Code/splintera-web/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 109, in get_response
    response = middleware_method(request, callback, callback_args, callback_kwargs)
  File "/home/imran/Code/splintera-web/venv/local/lib/python2.7/site-packages/splintera_client/tracer.py", line 24, in process_view
    return trace(view_func)(request, *view_args, **view_kwargs)
  File "/home/imran/Code/splintera-web/venv/local/lib/python2.7/site-packages/splintera_client/tracer.py", line 180, in wrapper
    result = f(*arg, **kw)
  File "/home/imran/Code/splintera-web/splintera/views.py", line 21, in dashboard
    db = mdb.connect('dbase.akbars.net','skunkwerk','motherlode721!','splintera_app')
  File "/home/imran/Code/splintera-web/venv/local/lib/python2.7/site-packages/MySQLdb/__init__.py", line 81, in Connect
    return Connection(*args, **kwargs)
  File "/home/imran/Code/splintera-web/venv/local/lib/python2.7/site-packages/MySQLdb/connections.py", line 187, in __init__
    super(Connection, self).__init__(*args, **kwargs2)
OperationalError: (1130, "Host '23-24-209-6-static.hfc.comcastbusiness.net' is not allowed to connect to this MySQL server")
WARNING 2013-07-05 10:25:49,046 base 6756 140163143399168 Not Found: /favicon.ico/
ERROR 2013-07-05 10:28:05,447 base 6756 140163143399168 Internal Server Error: /
Traceback (most recent call last):
  File "/home/imran/Code/splintera-web/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 109, in get_response
    response = middleware_method(request, callback, callback_args, callback_kwargs)
  File "/home/imran/Code/splintera-web/venv/local/lib/python2.7/site-packages/splintera_client/tracer.py", line 24, in process_view
    return trace(view_func)(request, *view_args, **view_kwargs)
  File "/home/imran/Code/splintera-web/venv/local/lib/python2.7/site-packages/splintera_client/tracer.py", line 180, in wrapper
    result = f(*arg, **kw)
  File "/home/imran/Code/splintera-web/splintera/views.py", line 21, in dashboard
    db = mdb.connect('dbase.akbars.net','skunkwerk','motherlode721!','splintera_app')
  File "/home/imran/Code/splintera-web/venv/local/lib/python2.7/site-packages/MySQLdb/__init__.py", line 81, in Connect
    return Connection(*args, **kwargs)
  File "/home/imran/Code/splintera-web/venv/local/lib/python2.7/site-packages/MySQLdb/connections.py", line 187, in __init__
    super(Connection, self).__init__(*args, **kwargs2)
OperationalError: (1130, "Host '23-24-209-6-static.hfc.comcastbusiness.net' is not allowed to connect to this MySQL server")
WARNING 2013-07-05 10:28:07,668 base 6756 140163143399168 Not Found: /favicon.ico/
WARNING 2013-07-05 10:28:35,732 base 6756 140163126613760 Not Found: /favicon.ico/
WARNING 2013-07-05 10:50:08,017 base 7030 140356142413568 Not Found: /favicon.ico/
WARNING 2013-07-05 10:54:30,725 base 7111 140604881237760 Not Found: /favicon.ico/
WARNING 2013-07-05 11:10:26,490 base 7328 139722936547072 Not Found: /favicon.ico/
WARNING 2013-07-05 11:11:25,286 base 7372 140614905575168 Not Found: /favicon.ico/
WARNING 2013-07-05 11:12:23,060 base 7424 139705331889920 Not Found: /favicon.ico/
WARNING 2013-07-05 11:22:38,955 base 7573 140524811572992 Not Found: /favicon.ico/
WARNING 2013-07-05 11:27:05,677 base 7641 140509538621184 Not Found: /favicon.ico/
